"""Generate DHLCT-C2-60 geometry from its manufacturer drawing (metres)."""
from pathlib import Path
import math
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parents[1]
MODEL_NAME = "DHLCT-C2-60"
MIN_HEIGHT, MAX_HEIGHT = 0.265, 1.270
STROKE, NO_LOAD_SPEED, LIFT_MASS, PAYLOAD_KG = 1.005, .016, 20.0, 60.0
# Drawing: 760 x 420 steel frame; catalog envelope width is 435 mm.
FRAME_LENGTH, FRAME_WIDTH = .760, .420
# Custom upper platform: user-specified 5 mm aluminium sheet, nominal density kg/m^3.
PLATFORM_THICKNESS, ALUMINIUM_DENSITY = .005, 2700.0
PLATFORM_MASS = FRAME_LENGTH*FRAME_WIDTH*PLATFORM_THICKNESS*ALUMINIUM_DENSITY
MOUNT_SPACING = .715
SPAN, AXLE_Z, TOP_OFFSET = 0.660, 0.055, 0.055
ARM_MASS = 2.475  # Four paired arms plus 0.1 kg carriage = 10 kg.
HALF_RISE = (MIN_HEIGHT - AXLE_Z - TOP_OFFSET) / 2
LENGTH = math.hypot(SPAN, HALF_RISE)
THETA = math.atan2(HALF_RISE, SPAN)
BLACK = "0.105 0.115 0.13 1"
METAL = "0.48 0.51 0.55 1"


def el(parent, tag, **attrs):
    return ET.SubElement(parent, tag, {k: str(v) for k, v in attrs.items()})


def xyz(*values):
    return " ".join(f"{v:.10f}" for v in values)


def box(parent, name, pos, size, color=BLACK, collision=False):
    return el(parent, "geom", name=name, type="box", pos=xyz(*pos),
              size=xyz(*size), rgba=color, mass="0",
              contype="2" if collision else "0", conaffinity="1" if collision else "0")


def pin(parent, name, x, y=0, radius=0.009, half=0.184):
    return el(parent, "geom", name=name, type="cylinder", pos=xyz(x, y, 0),
              size=xyz(radius, half), euler=xyz(math.pi/2, 0, 0),
              rgba=METAL, mass="0", contype="0", conaffinity="0")


def site(parent, name, x=0, z=0):
    el(parent, "site", name=name, pos=xyz(x, 0, z), size="0.003", rgba="0 0 0 0")


def arm(parent, name, pos, angle, sign, axis):
    body = el(parent, "body", name=name, pos=xyz(*pos), euler=xyz(0, angle, 0))
    el(body, "joint", name=name+"_hinge", type="hinge", axis=xyz(0, axis, 0), damping="0.4")
    # Two parallel bars and their crossbrace form one rigid assembly.
    roll_inertia = .062*ARM_MASS/2.725
    el(body, "inertial", pos=xyz(sign*LENGTH/2, 0, 0), mass=ARM_MASS,
       diaginertia=xyz(roll_inertia, ARM_MASS*LENGTH**2/12, roll_inertia+ARM_MASS*LENGTH**2/12))
    lane = 0.160 if name.endswith("a") else 0.133
    for side in (-1, 1):
        box(body, f"{name}_bar_{side}", (sign*LENGTH/2, side*lane, 0),
            (LENGTH/2+0.012, 0.010, 0.018))
    box(body, name+"_crossbrace", (sign*LENGTH*0.22, 0, 0), (0.015, lane, 0.012))
    for label, fraction in (("root", 0), ("center", .5), ("tip", 1)):
        pin(body, name+"_"+label+"_pin", sign*LENGTH*fraction)
        site(body, name+"_"+label, sign*LENGTH*fraction)
    return body


def build():
    root = ET.Element("mujocoinclude")
    root.append(ET.Comment(" Generated by scripts/build_scissor_lift.py. DHLCT-C2-60: 60 kg nominal payload, 20 kg lift mass, 265-1270 mm height. Manufacturer drawing: 760 x 420 mm steel frame; catalog envelope: 760 x 435 mm. Internal geometry/inertias estimated. "))
    base = el(root, "body", name="scissor_lift_base", pos="0 0 0.05")
    el(base, "inertial", pos="0 0 0.045", mass="4.5", diaginertia="0.072 0.216 0.279")
    for side in (-1, 1):
        box(base, f"base_rail_{side}", (0, side*.190, .035), (.360, .020, .025), collision=True)
        box(base, f"base_mount_bar_{side}", (side*.360, 0, .005), (.020, .210, .005), collision=True)
        for end in (-1, 1):
            box(base, f"base_stop_{side}_{end}", (end*.310, side*.190, .115), (.013, .013, .055))
    for side in (-1, 1):
        box(base, f"base_inner_crossbar_{side}", (side*.105, 0, .005), (.020, .210, .005))
    fixed = el(base, "body", name="base_fixed_axle", pos=xyz(SPAN/2, 0, AXLE_Z))
    pin(fixed, "base_fixed_pin", 0)
    lower_a = arm(base, "lower_a", (SPAN/2, 0, AXLE_Z), THETA, -1, 1)
    upper_a = arm(lower_a, "upper_a", (-LENGTH, 0, 0), -2*THETA, 1, 1)

    slider = el(base, "body", name="base_carriage", pos=xyz(-SPAN/2, 0, AXLE_Z))
    el(slider, "joint", name="base_slider", type="slide", axis="1 0 0", range="0 0.40", damping="1")
    el(slider, "inertial", pos="0 0 0", mass="0.1", diaginertia="0.003 0.00005 0.003")
    for side in (-1, 1):
        pin(slider, f"bottom_roller_{side}", 0, side*.178, .021, .008)
    lower_b = arm(slider, "lower_b", (0, 0, 0), -THETA, 1, -1)
    upper_b = arm(lower_b, "upper_b", (LENGTH, 0, 0), 2*THETA, -1, -1)
    for side in (-1, 1):
        pin(upper_b, f"top_roller_{side}", -LENGTH, side*.178, .021, .008)

    # Actuator pins: 20% along lower B to 25% along upper B.
    # Hinge plus passive telescope follows the actual scissor loop.
    dx, dz = .55*SPAN, 1.05*HALF_RISE
    actuator_length = math.hypot(dx, dz)
    actuator_angle = math.atan2(dz, dx)
    cylinder = el(lower_b, "body", name="actuator_barrel", pos=xyz(.2*LENGTH, 0, 0),
                  euler=xyz(0, THETA-actuator_angle, 0))
    el(cylinder, "joint", name="actuator_pitch", type="hinge", axis="0 1 0", damping="0.05")
    el(cylinder, "inertial", pos="0.13 0 0", mass="1.5", diaginertia="0.002 0.015 0.015")
    box(cylinder, "actuator_black_housing", (.145, 0, 0), (.145, .025, .025))
    box(cylinder, "actuator_gearbox", (.035, 0, -.025), (.045, .042, .033))
    pin(cylinder, "actuator_motor", .025, -.070, .034, .055)
    pin(cylinder, "actuator_bottom_pin", 0, 0, .011, .045)
    rod = el(cylinder, "body", name="actuator_rod", pos=xyz(actuator_length, 0, 0))
    el(rod, "joint", name="actuator_extension", type="slide", axis="1 0 0", damping="1")
    el(rod, "inertial", pos="-0.16 0 0", mass="0.5", diaginertia="0.0001 0.0043 0.0043")
    el(rod, "geom", name="actuator_piston", type="cylinder", fromto="-0.36 0 0 0 0 0",
       size="0.014", mass="0", rgba=METAL, contype="0", conaffinity="0")
    pin(rod, "actuator_upper_pin", 0, 0, .011, .045)
    site(rod, "actuator_tip")
    site(upper_b, "actuator_attachment", -.25*LENGTH)

    top = el(base, "body", name="lift_top", pos=xyz(0, 0, MIN_HEIGHT-.020))
    el(top, "joint", name="lift_joint", type="slide", axis="0 0 1", range=xyz(0, STROKE), damping="15")
    el(top, "inertial", pos="0 0 -0.012", mass="3.5", diaginertia="0.051625 0.1645 0.21525")
    for side in (-1, 1):
        # Rail top touches mounting-bar underside at local z=0 (no 10 mm gap).
        box(top, f"top_rail_{side}", (0, side*.190, -.030), (.360, .020, .030), collision=True)
    for index, x in enumerate((-MOUNT_SPACING/2, MOUNT_SPACING/2)):
        box(top, f"top_mount_bar_{index}", (x, 0, .010), (.020, .210, .010), collision=True)
        # Dark circular markings indicate mounting-hole locations; no CAD booleans.
        for j, y in enumerate((-.1945, .1945)):
            el(top, "geom", name=f"mount_hole_mark_{index}_{j}", type="cylinder",
               pos=xyz(x, y, .0201), size=xyz(.0055, .00015),
               rgba="0.015 0.018 0.02 1", mass="0", contype="0", conaffinity="0")
    site(top, "top_fixed_attachment", SPAN/2, -.035)
    # Separate body keeps the added plate's physical inertia outside the 20 kg lift.
    # Its underside sits on the mounting bars; the robot sits on its upper face.
    platform = el(top, "body", name="upper_platform", pos="0 0 0.020")
    plate = box(platform, "aluminium_upper_platform", (0, 0, PLATFORM_THICKNESS/2),
                (FRAME_LENGTH/2, FRAME_WIDTH/2, PLATFORM_THICKNESS/2),
                "0.72 0.76 0.81 1", collision=True)
    plate.set("mass", str(PLATFORM_MASS))
    mount = el(platform, "body", name="kinova_mount", pos=xyz(0, 0, PLATFORM_THICKNESS))
    el(mount, "include", file="kinova_gen3_body.xml")
    ET.indent(root, space="    ")
    ET.ElementTree(root).write(ROOT / "models/scissor_lift.xml", encoding="unicode")


if __name__ == "__main__":
    build()
